### PR TITLE
TUA - Journey Management - Appointment Reference (Doc/gh 734)

### PR DESCRIPTION
**Pull request by skhasgiw-SPA**
TUA - Journey Management - Appointment Reference feature documentation is ready for final review.

Closes GH-734

### CODE REVIEW

**Comment by skhasgiw-SPA** [comment]
Hello Deb,

Please provide final review support to the **Journey Management - Appointment Reference** feature documentation. From the attached zip file, open _Journey Management - Appointment Reference - Spartacus Documentation.html_ page in the browser.
[Journey Management - Appointment Reference - Spartacus Documentation.zip](https://github.com/SAP/spartacus-docs/files/5268366/Journey.Management.-.Appointment.Reference.-.Spartacus.Documentation.zip)

**Review by DeborahCCJ — APPROVED** [review]
I have made updates to the appointment reference...

**Comment by skhasgiw-SPA** [comment]
Review comments received from Deb are incorporated in the updated ZIP documentation. 

[Journey Management - Appointment Reference - Spartacus Documentation.zip](https://github.com/SAP/spartacus-docs/files/5463957/Journey.Management.-.Appointment.Reference.-.Spartacus.Documentation.zip)

**Comment by gladius-mtl** [comment]
Content updated manually

**Pull request closed without merging**
